#!/bin/bash

URL="http://localhost:8080"
USR_ADMIN="admin"
PWSD_ADMIN="admin"

USR_ALUM="alum"
PWD_ALUM="alum"

function printInfo {
    echo -e "\e[1m\e[96m$1\e[0m\c"
}

########################

function test {
    endpoint=${URL}$1
    method=$2
    data=$3
    test_string=$4

    command="curl -d ${data} -X ${method} "${endpoint}"  2> /dev/null"
    OUT=$(eval ${command})


    if [[ $OUT == *"${test_string}"* ]]; then
      echo -e "\e[1m\e[92m\e[1m...PASSED\e[0m"
    else
      echo -e "\e[1m\e[91m\e[1m...FAIL\e[0m"
    fi
    echo -e "\e[93m»»» Tested with command:\e[95m \e[1m ${command}\e[0m"

     echo $OUT
     echo ""

}


# GET THE TOKEN FOR THE ADMIN
curl  -d  "username=${USR_ADMIN}&password=${PWSD_ADMIN}" -X POST "http://localhost:8080/auth/login" -s | cut -d : -f 2 | cut -d, -f 1 > admin.token~
TOKEN_ADMIN=$(cat admin.token~ | sed -r 's/["]+//g')

# GET THE TOKEN FOR THE ALUMNO
curl  -d  "username=${USR_ALUM}&password=${PWD_ALUM}" -X POST "http://localhost:8080/auth/login" -s | cut -d : -f 2 | cut -d, -f 1 > admin.token~
TOKEN_ALUMNO=$(cat admin.token~ | sed -r 's/["]+//g')

#TEST SOME ENDPOINTS

printInfo "»» Trying to login with invalid credentials."
test /auth/login POST "'username=admin&password=admin'" ":null"

printInfo "»» Trying to login with valid credentials for ADMIN user."
test /auth/login POST "'username=${USR_ADMIN}&password=${PWSD_ADMIN}'" ':"ok"'


printInfo "»» Trying to login with valid credentials for ALUMNO user."
test /auth/login POST "'username=${USR_ALUM}&password=${PWD_ALUM}'" ':"ok"'


printInfo "»» Show all billboards for user ADMIN."
test /carteleras?token=${TOKEN_ADMIN} GET "''" '['


printInfo "»» Show all billboards for user ALUMNO."
test /carteleras?token=${TOKEN_ALUMNO} GET  "''" '['

printInfo "»» Don't show all billboards for a invalid token."
test /carteleras?token=435g GET  "''" '403'

printInfo "»» Don't show all billboards for a invalid token."
test /carteleras?token=435g GET  "''" '403'

printInfo "»» Admin user can add a billboard."
test /carteleras?token=${TOKEN_ADMIN} POST   "'@billboard1.json' -H 'Content-Type: application/json'" 'TEST_BILLBOARD'

printInfo "»» Alumno user can't add a billboard."
test /carteleras?token=${TOKEN_ALUMNO} POST   "'@billboard1.json' -H 'Content-Type: application/json'" '403'



#REMOVE FILE GENERATED BY THIS TEST
rm *.token~