#!/bin/bash

URL="http://localhost:8080"


function printInfo {
    echo -e "\e[96m$1\e[0m\c"
}

########################

function test {
    endpoint=${URL}$1
    method=$2
    data=$3
    test_string=$4
    save_token=$5
    ref_token=$6

    OUT=$(curl -d "${data}" -X ${method} "${endpoint}" 2> /dev/null)


    if [[ $OUT == *"${test_string}"* ]]; then
      echo -e "\e[1m\e[92m..PASSED\e[0m"
    else
      echo -e "\e[1m\e[91m..FAIL\e[0m"
    fi
    echo -e "\e[33m»»» URL Tested: ${endpoint}\e[0m"
     echo $OUT
     echo ""
}


printInfo "»» Trying to login with invalid credentials."
test /auth/login POST "username=admin&password=admin" ":null"

printInfo "»» Trying to login with valid credentials for ADMIN user."
test /auth/login POST "username=cris&password=123456" ':"ok"'

# GET THE TOKEN FOR THE ADMIN
curl  -d  "username=cris&password=123456" -X POST "http://localhost:8080/auth/login" -s | cut -d : -f 2 | cut -d, -f 1 > admin.token~
TOKEN_ADMIN=$(cat admin.token~ | sed -r 's/["]+//g')

# GET THE TOKEN FOR THE ALUMNO
curl  -d  "username=cris&password=123456" -X POST "http://localhost:8080/auth/login" -s | cut -d : -f 2 | cut -d, -f 1 > admin.token~
TOKEN_ALUMNO=$(cat admin.token~ | sed -r 's/["]+//g')


printInfo "»» Trying to login with valid credentials for ALUMNO user."
test /auth/login POST "username=cris&password=123456" ':"ok"'


printInfo "»» Show all billboards for user ADMIN."
test /carteleras?token=${TOKEN_ADMIN} GET "" '{"id"'


printInfo "»» Show all billboards for user ALUMNO."
test /carteleras?token=${TOKEN_ALUMNO} GET  "" '{"id"'


printInfo "»» Don't show all billboards for a invalid token."
test /carteleras?token=435g GET  "" '403'

#REMOVE FILE GENERATED BY THIS TEST
rm *.token~
